name: wavenetsoftphone
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.9+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.0
  sip_ua: 1.0.1
  flutter_webrtc: ^0.12.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2
  flutter_ringtone_player: ^4.0.0
  audioplayers: ^6.5.1
  flutter_foreground_task: ^6.2.0
  change_app_package_name: ^1.5.0
  flutter_callkit_incoming: ^3.0.0
  uuid: ^4.4.2
  http: ^1.2.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/icons/ic_notification.png
    - assets/sounds/finder.mp3
    - env

# ðŸ‘‡ place this OUTSIDE the `flutter:` block!
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#3D5AFE"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
